config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'homes/top', to: 'homes#top'
  get 'homes/about', to: 'homes#about'
  get 'users/event', to: 'users#event'

  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      resources :calenders, only: [:index, :create, :destroy, :update, :new]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calender.rb
class Calender < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  attachment :image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :menu, presence: true
  validates :title, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  private
  def post_image_params
    params.require(:post_image).permit(:image)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :calenders, dependent: :destroy
  attachment :profile_image

  def posts
    return PostImage.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sugn_up, keys: [:name])
  end
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController

  def index
    @user = User.find(params[:id])
    @calenders = Calender.where(user_id: @user.id)
    @calender = Calender.new
    @calenders = Calender.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @calenders}
      format.json { render :json => @calenders}
    end
  end

  def create
    @calender = Clender.new(calender_params)
    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: 'Event was successfully created.' }
        format.json { render :index, status: :created, location: @calender }
      else
        format.html { render :new }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_event
    @calender = Calender.find(params[:id])
  end

  def calender_params
    params.require(:calender).permit(:title, :start, :end, :user_id, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment, :image)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
   @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private
  def post_image_params
    params.require(:post_image).permit(:menu, :image, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calenders/index.html.erb
<div id="calendar"></div>

app/views/homes/about.html.erb
<div class="about">
  <div class="about__main">
    <%= image_tag 'image1.jpg' %>
    <h2 class="about__title">Muscle_Dairyについて</h2>
    <div class="bg1"></div>
  </div>

  <div class="about__greeting">
    <div class="about__contents">
      <%= image_tag 'image4.jpg' %>
      <div class="about__content">
        <h2 class="about__title2">Muscle_Dairyの使い方</h2>
        <p>このサイトは日々の筋トレを記録出来る筋トレ日記のようなサイトです。</p>
        <p>１日の終わりに今日やった筋トレのメニューや自分の画像を投稿し、いつでも見返すことができます。</p>
      </div>
    </div>
  </div>
  <div class="about__greeting">
    <div class="about__contents">
      <div class="about__content">
        <h2 class="about__title2">Muscle_Dairyを作成した理由</h2>
        <p>自分は筋トレを始めようと思ってもいつも長続きしませんでした。</p>
        <p>しかし、プログラミング学習は継続して続けられている。</p>
        <p>そこで、プログラミング学習のように毎日の目標設定と自分がやった事をアウトプットする事が大事だと気付き</p>
        <p> これらを日記のように記録出来るこのサイトを作成しました。</p>
      </div>
      <%= image_tag 'image0.jpg' %>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="top">
  <ul class="bxslider">
    <li class="top__title"><%= image_tag 'image8.jpg' %>
      <h1 class="top__title">Muscle_Dairy</h1>
      <p class="top__sub-title">筋トレが好きな人のために</p>
    </li>
    <li class="top__title"><%= image_tag 'image6.jpg' %>
      <h1 class="top__title">Muscle_Dairy</h1>
      <p class="top__sub-title">これから筋トレを始めたい人のために</p>
    </li>
    <li class="top__title"><%= image_tag 'image7.jpg' %>
      <h1 class="top__title">Muscle_Dairy</h1>
      <p class="top__sub-title">今まで挫折してきた人のために</p>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MuscleDairy</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body data-turbolinks="false">
  <header>
    <div class="header_bar row">
      <span class="header__logo col-xs-7">
        <%= link_to image_tag('Muscle-Dairy.png'), root_path %><br>
      </span>
      <% if user_signed_in? %>
      <div class="user_nav col-xs-5 header-content">
        <div><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn header-right" %></div>
        <div><%= link_to "画像投稿", new_post_image_path, class: "btn btn-default navbar-btn header-right" %></div>
        <div><%= link_to "タイムライン", post_images_path, class: "btn btn-default navbar-btn header-right" %></div>
        <div><%= link_to "マイページ", user_path(current_user.id), class: "btn btn-default navbar-btn header-right" %></div>
        <div><%= link_to "カレンダー", calenders_path(current_user.id), class: "btn btn-default navbar-btn header-right" %></div>
      </div>
      <% else %>
      <div class="col-xs-5 header-content">
        <div><%= link_to "Top", homes_top_path, class: "btn btn-default navbar-btn header-right" %></div>
        <div><%= link_to "About", homes_about_path, class: "btn btn-default navbar-btn header-right" %></div>
        <div> <%= link_to "ログイン", new_user_session_path, class: "btn btn-default navbar-btn header-right" %></div>
        <div> <%= link_to "新規登録", new_user_registration_path, class: "btn btn-default navbar-btn header-right" %></div>
      </div>
      <% end %>
  </header>

  <%= yield %>

  <footer>
    <p>(c)copy right</p>
  </footer>

</body>

<script>
  $(document).ready(function() {
    $('.bxslider').bxSlider({
      auto: true, // 自動スライド
      speed: 1500, // スライドするスピード
      moveSlides: 3, // 移動するスライド数
      pause: 2500, // 自動スライドの待ち時間
      maxSlides: 1, // 一度に表示させる最大数
      randomStart: true, // 最初に表示するスライドをランダムに設定
      autoHover: true, // ホバー時に自動スライドを停止
      mode: 'fade'
    });
  });
</script>

</html>

app/views/post_images/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @post_images.each do |post_image| %>
      <div class="timeline">
        <div class="timeline__top-info">
          <div class="timeline__profile-image">
            <%= attachment_image_tag post_image.user, :profile_image, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "30×30" %>
          </div>
          <div class="timeline__name">
            <h2><%= post_image.user.name %></h2>
          </div>
        </div>

        <div class="timeline__main-image">
          <%= link_to post_image_path(post_image.id) do %>
          <%= attachment_image_tag post_image, :image %>
          <% end %>
        </div>
        <div class="timeline__info">
          <h3 class="timeline__menu">
            <%= link_to post_image_path(post_image.id) do %>
            <%= post_image.title %>
            <% end %>
          </h3>
          <p class="timeline__title"><%= post_image.menu %></p>
          <ul class="timeline__comment">
            <li>
              <%= link_to "#{post_image.post_comments.count} 件コメントをすべて見る", post_image_path(post_image.id) %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3 post_image_form">

    <div class="section-title-content">
      <h3 class="section-title">
        <span>画像投稿フォーム</span>
      </h3>
    </div>

    <%= form_for(@post_image, url: post_images_path) do |f| %>
    <% if @post_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
      <ul>
        <% @post_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <div class="item-image">
          <%= attachment_image_tag @post_image , :image, class: "img-square view-image", fallback: "no_image.jpg" %>
        </div>
        <%= f.attachment_field :image, placeholder:"画像" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.text_area :menu, class: "form-control", size: "70x5", placeholder:"menu" %>
        <%= f.text_area :title, class: "form-control", size: "70x5",placeholder: "今日の感想" %>
      </div>
    </div>
    <br>
    <%= f.submit "投稿", class:"btn btn-block" %>
    <% end %>
  </div>
</div>
<script>
  $(function() {
    // inputのidから情報の取得
    $('#post_image_image').on('change', function(e) {
      // ここから既存の画像のurlの取得
      var reader = new FileReader();
      reader.onload = function(e) {
        $(".view-image").attr('src', e.target.result);
      }
      // ここまで
      reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
    });
  });
</script>

app/views/post_images/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="mypage">
        <div class="mypage__info">
          <div class="mypage__top-info">
            <div class="mypage__profile-image">
              <%= attachment_image_tag @post_image.user, :profile_image, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "30×30" %>
            </div>
            <div class="mypage__name">
              <h2><%= @post_image.user.name %></h2>
            </div>
          </div>

          <div class="mypage__main-image">
            <%= attachment_image_tag @post_image, :image %>
          </div>

          <div class="mypage__bottom-info">
            <div class="mypage__calender">
              <i class="far fa-calendar-alt"></i>
              <%= @post_image.created_at.strftime('%Y/%m/%d') %>
            </div>
            <div class="mypage__comment-icon">
              <i class="fa fa-comment">
                <a href="#comments"><%= @post_image.post_comments.count %></a>
              </i>
            </div>
            <div class="mypage__favorite">
              <% if @post_image.favorited_by?(current_user) %>
              <div class="mypage__favorite-count">
                <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" , style="color: red;"></i>
                <%= @post_image.favorites.count %>いいね
                <% end %>
              </div>
              <% else %>
              <div class="mypage__favorite">
                <%= link_to post_image_favorites_path(@post_image), method: :post do %>
                <i class="fa fa-heart" aria-hidden="true"></i>
                <%= @post_image.favorites.count %>いいね
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
          <div class="mypage__btn">
            <% if @post_image.user == current_user %>
            <%= link_to "削除", post_image_path(@post_image), method: :delete, data: {confirm: "本当にこの投稿を削除してもよろしいですか？"} , class: "btn btn-danger" %>
            <% end %>
          </div>
          <div class="mypage__title">
            <h2><%= @post_image.title %></h2>
          </div>
          <div class="mypage__menu">
            <p><%= @post_image.menu %></p>
          </div>
        </div>
        <div class="mypage__comment">
          <% @post_image.post_comments.each do |post_comment| %>
          <div class="mypage__comment-content">
            <div class="mypage__comment-image">
              <%= attachment_image_tag post_comment.user, :profile_image, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "30×30" %>
            </div>
            <div class="mypage__comment-text">
              <%= post_comment.user.name %>
              <div class="mypage__comment-meta">
                <span><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
              </div>
              <div class="mypage__comment-entry"><%= post_comment.comment %></div>
              <% if post_comment.user == current_user %>
              <div class="mypage__comment-btn">
                <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除してもよろしいですか？"} %>
              </div>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
        <%= form_for [@post_image, @post_comment] do |f| %>
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
          </div>
        </div>
        <%= f.submit "送信する", class: "btn btn-primry" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="user-edit">
    <div class="col-xs-8 col-xs-offset-2">
      <h2 class="user-edit__title">プロフィール編集</h2>
      <%= form_for(@user) do |f| %>
      <div class="user-edit__form-group">
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
        <%= f.label :名前 %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "neme", placeholder:"名前" %>
      </div>
      <div class="user-edit__form-group">
        <span class="fa fa-envelope form-control-icon" aria-hidden="true"></span>
        <%= f.label :メールアドレス %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder:"メールアドレス" %>
      </div>
      <div class="user-edit__image">
        <span class="fas fa-images form-control-icon" aria-hidden="true"></span>
        <%= f.label :プロフィール画像 %><br />
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle" %>
      </div>
      <div class="form-group has-icon">
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit__form" %>
      </div>
      <%= f.submit "変更を保存", class:"btn btn-lg btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="user-page">
      <div class="col-xs-12">
        <div class="user-page__content">
          <h1 class="user-page__title">マイページ</h1>
          <div class="user-page__top-info">
            <div class="user-page__profile-image">
              <%= attachment_image_tag @user, :profile_image, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg", size: "30×30" %>
            </div>
            <div class="user-page__name">
              <h2><%= @user.name %></h2>
            </div>
          </div>
          <% if @user.id == current_user.id %>
          <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right btn btn-primary" %></p>
          <% end %>
          <table class="user-page__table table table-bordered">
            <tr>
              <th>名前</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= @user.email %></td>
            </tr>
          </table>
          <div class="user-page__my-image">
            <div class="user-page__image-box">
              <% @user.posts.each do |postImage| %>
              <%= link_to post_image_path(postImage.id) do %>
              <%= attachment_image_tag postImage , :image %>
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_html.erb
<div class="row">
  <div class="user-page">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="user-page__content">
        <h3 class="profile-name"><%= @user.name %></h3>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img" %>
        <% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>
        <% end %>
        <%= paginate @post_images %>
      </div>
    </div>
  </div>
</div>